/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/registro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/monitoreo` | `/monitoreo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion/debug` | `/configuracion/debug`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil/editar` | `/perfil/editar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/registro`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/monitoreo` | `/monitoreo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracion/debug` | `/configuracion/debug`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil/editar` | `/perfil/editar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/registro${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/monitoreo${`?${string}` | `#${string}` | ''}` | `/monitoreo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracion/debug${`?${string}` | `#${string}` | ''}` | `/configuracion/debug${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/configuracion${`?${string}` | `#${string}` | ''}` | `/configuracion${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil/editar${`?${string}` | `#${string}` | ''}` | `/perfil/editar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/registro`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/monitoreo` | `/monitoreo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion/debug` | `/configuracion/debug`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil/editar` | `/perfil/editar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
